# Generated by Django 3.2 on 2022-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_achievementcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementcat',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='achievementcat',
            name='cat',
        ),
        migrations.AddField(
            model_name='achievementcat',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
