# Generated by Django 3.2 on 2022-05-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20220516_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementcat',
            name='name',
        ),
        migrations.AddField(
            model_name='achievementcat',
            name='achievement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cats.achievement'),
            preserve_default=False,
        ),
    ]
